// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef eps_win_hpp
#define eps_win_hpp
#include <FL/Fl.H>
#undef Status
#include "widgets.hpp"
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Box.H>

class EpsWindow : public Fl_Window {
  void _EpsWindow();
public:
  EpsWindow(int X, int Y, int W, int H, const char *L = 0);
  EpsWindow(int W, int H, const char *L = 0);
  EpsWindow();
  itc::eps::TlmWidgetMap tlm; 
  Fl_Light_Button *nos_status_out;
  Fl_Value_Output *sim_time_out;
  Fl_Value_Output *firmware_out;
  Fl_Value_Output *revision_out;
  Fl_Output *checksum_out;
  Fl_Value_Output *reset_power_on_out;
  Fl_Value_Output *reset_brown_out;
  Fl_Value_Output *reset_manual_out;
  Fl_Value_Output *reset_wdt_out;
  Fl_Light_Button *status_out[7];
  Fl_Output *error_code_out;
  Fl_Output *error_msg_out;
  itc::eps::SwitchButton *switch_in[10];
};
#endif
